name: Debug SSH Secret

on:
  workflow_dispatch:   # 手动触发，避免每次push都跑

jobs:
  debug:
    runs-on: self-hosted
    steps:
      - name: Check if SSH_PRIVATE_KEY is injected
        run: |
          if [ -z "${SSH_PRIVATE_KEY}" ]; then
            echo "❌ Secret SSH_PRIVATE_KEY is EMPTY or not injected"
            exit 1
          else
            echo "✅ Secret loaded"
            echo "Length: ${#SSH_PRIVATE_KEY}"
            echo "First 50 chars:"
            echo "${SSH_PRIVATE_KEY:0:50}..."
          fi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

          