name: Build RK3568 (qmake Release)

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    env:
      # 工具链与 qmake 路径 —— 按需改成你的实际路径
      
      TOOLCHAIN: /rk3568/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu
      GCC_BIN:  /rk3568/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/
      QMAKE:    /rk3568/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/Qt-5.14.2-arm64/bin/qmake

      # 你的 .pro 文件名
      PRO_FILE: modbus_tool.pro

      # 可选：VMware 共享目录（若不需要可删掉“Copy to VMware share”步骤）
      SHARE_DIR: /mnt/hgfs/share

      # 并发编译度（make 会自动读取）
      MAKEFLAGS: -j4

    steps:

      # 1) 拉取代码（复用本机 ~/.ssh/id_ed25519，不用 secrets）
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      # 2) 显示工具链与 qmake 信息
      - name: Show toolchain & qmake
        run: |
          export PATH="$GCC_BIN:$(dirname "$QMAKE"):$PATH"
          which aarch64-none-linux-gnu-gcc
          which aarch64-none-linux-gnu-g++
          "$QMAKE" -v

      # 3) 干净构建目录
      - name: Clean build dir
        run: |
          rm -rf build
          mkdir -p build

      # 4) qmake 生成 Makefile（Release）
      - name: Configure (qmake, Release)
        run: |
          export PATH="$GCC_BIN:$(dirname "$QMAKE"):$PATH"
          cd build
          "$QMAKE" "../$PRO_FILE" \
            CONFIG+=release \
            QMAKE_CC=aarch64-none-linux-gnu-gcc \
            QMAKE_CXX=aarch64-none-linux-gnu-g++ \
            QMAKE_LINK=aarch64-none-linux-gnu-g++


      # 5) 编译
      - name: Build
        run: |
          export PATH="$GCC_BIN:$(dirname "$QMAKE"):$PATH"
          cd build
          make

      # 6) （可选）strip 瘦身
      - name: Strip binary (optional)
        run: |
          if [ -f build/DistAreaVoltCtrl ]; then
            aarch64-none-linux-gnu-strip build/DistAreaVoltCtrl || true
          fi

      # 7) 上传产物到 GitHub（Actions 页面→Artifacts 可下载）
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rk3568-build
          path: |
            build/DistAreaVoltCtrl
            build/*.so
            build/*.a
          if-no-files-found: warn

      # 8) （可选）拷到 VMware 共享目录，Windows 立刻可见
      - name: Copy to VMware share (optional)
        run: |
          if [ -d "$SHARE_DIR" ]; then
            mkdir -p "$SHARE_DIR/voltctrl-build"
            rsync -av build/ "$SHARE_DIR/voltctrl-build/"
            echo "Copied to $SHARE_DIR/voltctrl-build/"
          else
            echo "Share dir $SHARE_DIR not found. Skip copy."
          fi